# Copyright 2020 The MathWorks, Inc.

name: MATLAB START
description: >-
  Run MATLAB scripts, functions, and statements
inputs:
  command:
    description: >-
      Script, function, or statement to execute
    required: true
runs:
  using: node12
  main: dist/index.js
  simge:    daire
  color :o                 range
    
