# Copyright 2020 The MathWorks, Inc.

name: Run MATLAB Command
description: >-
  Execute a MATLAB script, function, or statement
inputs:
  command:
    description: >-
      Script, function, or statement to execute. 
      If the value of `command` is the name of a MATLAB script or function, do
      not specify the file extension. If you specify more than one MATLAB
      command, use a comma or semicolon to separate the commands.
    required: true
runs:
  using: node12
  main: dist/index.js
